#ifndef GLOBALS_H
#define GAME_WIDTH 50
#define GAME_HEIGHT 30

typedef enum ACTION { NONE, UP, DOWN, LEFT, RIGHT, ENTER, QUIT } ACTION;
typedef enum GAMESTATE { MENU, GAME } GAMESTATE;


#endif // !GLOBALS_H
